soundOnDeath:
    enable: true
    soundId: TonyIggy-Astronomia
herobrine:
    usernameSkin: Herobrine
    totemEnable: true
    armor: true
    drops:
        enable: true
        maxQuantity: 3
        minQuantity: 1