herobrine:
  totemEnable: true
  armor: true
  drops:
    quantity: 3
custommobs:
  - holycow:
      displayname: Holycow
      type: COW
      disguise: NeXiPL
  - holybee:
      displayname: Holybee
      type: BEE
      disguise: NeXiPL