name: BetterMC
version: '${project.version}'
main: me.nexipl.bettermc.BetterMC
api-version: 1.19
description: 'BetterMC - ${project.version}'
softdepend:
  - LibsDisguises
  - NBTAPI
  - PlaceholderAPI
  - Multiverse-Core
commands:
  distest:
    usage: /distest
    description: Test
  spawnentity:
    usage: /spawnentity
    description: Spawn custom entity
  bettermcreload:
    usage: /bettermcreload
    description: BetterMC reload