name: BetterMC
version: '${project.version}'
main: me.nexipl.bettermc.BetterMC
api-version: 1.20
description: 'BetterMC - ${project.version}'
depend:
  - LibsDisguises
  - ProtocolLib
softdepend:
  - dynmap v3.7-beta-3-932
  - PlaceholderAPI
commands:
  bettermcreload:
    usage: /bettermcreload
    description: BetterMC reload
    permission: bettermc.bettermcreload
  bettermc:
    usage: /bettermc
    description: BetterMC
    permission: bettermc.bettermc
  getchestbox:
    usage: /getchestbox
    description: BetterMC
    permission: bettermc.getchestbox
  getchestkey:
    usage: /getchestkey
    description: BetterMC
    permission: bettermc.getchestkey