name: BetterMC
version: '${project.version}'
main: me.nexipl.bettermc.BetterMC
api-version: 1.20
description: 'BetterMC - ${project.version}'
depend:
  - LibsDisguises
  - ProtocolLib
softdepend:
  - PlaceholderAPI
commands:
  spawnentity:
    usage: /spawnentity
    description: Spawn custom entity
  bettermcreload:
    usage: /bettermcreload
    description: BetterMC reload
  bettermc:
    usage: /bettermc
    description: BetterMC